from .add_group import *
from .add_stuff import *
from .add_subject import *
from .application import *
from .cancel_lesson import *
from .add_user_to_group import *
from .news import *
from .cancel_all_lessons import *
from .gen_cer import *